"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { useMemo } from "react";

import {
  ConnectionProvider,
  WalletProvider,
} from "@solana/wallet-adapter-react";
import { clusterApiUrl } from "@solana/web3.js";
import "@solana/wallet-adapter-react-ui/styles.css";
import {
  WalletModalProvider,
  // WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import {
  PhantomWalletAdapter as getPhantomWallet,
  ParticleAdapter as getParticleWallet,
  SolflareWalletAdapter as getSolflareWallet,
  SolongWalletAdapter as getSolongWallet,
  CoinbaseWalletAdapter as getCoinbaseWallet,
  LedgerWalletAdapter as getLedgerWallet,
  Coin98WalletAdapter as getCoin98Wallet,
} from "@solana/wallet-adapter-wallets";
import Link from "next/link";
import WalletMultiButton from "@/components/WalletMultiButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const endpoint = clusterApiUrl("devnet");
  const wallets = useMemo(
    () => [
      new getPhantomWallet(),
      new getParticleWallet(),
      new getSolongWallet(),
      new getSolflareWallet(),
      new getCoinbaseWallet(),
      new getLedgerWallet(),
      new getCoin98Wallet(),
    ],
    []
  );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConnectionProvider endpoint={endpoint}>
          <WalletProvider wallets={wallets} autoConnect>
            {/* {console.log(wallets)} */}
            <WalletModalProvider>
              <header className=" flex justify-between items-center p-2 border-b">
                <div className="">
                  <ol className="flex list-none gap-2">
                    <li>
                      <Link href="/">Home</Link>
                    </li>
                    <li>
                      <Link href="/account">Account</Link>
                    </li>
                    <li>
                      <Link href="/account/send">Send</Link>
                    </li>

                    <li>
                      <Link href="/account/query">Query</Link>
                    </li>

                    <li>
                      <Link href="/ping">Ping</Link>
                    </li>

                    <li>
                      <Link href="/pay-ui">Pay UI</Link>
                    </li>
                  </ol>
                </div>
                <WalletMultiButton />
                {/* <WalletMultiButton className="p-0 m-0 h-5" /> */}
              </header>
              {children}
            </WalletModalProvider>
          </WalletProvider>
        </ConnectionProvider>
      </body>
    </html>
  );
}
